config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:create]
  end
end


# restaurant_reviews POST /restaurants/:restaurant_id/reviews(.:format) | reviews#create
# new_restaurant_review GET  /restaurants/:restaurant_id/reviews/new(.:format) | reviews#new
# restaurants GET  /restaurants(.:format) | restaurants#index
# POST /restaurants(.:format) | restaurants#create
# new_restaurant GET  /restaurants/new(.:format) | restaurants#new
# restaurant GET  /restaurants/:id(.:format) | restaurants#show

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5] }, numericality: {only_integer: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # before_action :fetch_restaurant, only: :show

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def restaurant_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end

  # def fetch_restaurant
  #   @restaurant = Restaurant.find(params[:id])
  # end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :fetch_restaurant
  # def new
  #   @review = Review.new
  # end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save
    if @review.save
      redirect_to @restaurant
    else
      render "restaurants/show"
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating, :restaurant_id)
  end

  # Get restaurant ID from the URL
  def fetch_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
     <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar justify-content-between navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/restaurants">Restaurants</a>

      <div id="navbarSupportedContent">
        <div class="ml-auto flex">
          <a class="btn btn-outline-primary my-2 my-sm-0 ml-2" href="/restaurants/new">Add Restaurant</a>
        </div>
      </div>
    </nav>
    <div class="container mt-3">
      <%= yield %>
    </class>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>

  <% if @restaurant.errors.any? %>
    <div class="alert alert-danger">
      <h3>Please fix these problems:</h3>
      <ul>
      <% @restaurant.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :category %>
    <%= f.input :phone_number %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary mb-3' %>
  </div>
<% end %>

app/views/restaurants/index.html.erb
<h1>Restaurant List</h1>
<ul class="list-unstyled mt-4">
<% @restaurants.each do |r| %>
  <li class = "mb-3"> 🍽 <%= r.name %> <%= link_to "See details", restaurant_path(r), class: "btn btn-light btn-sm pull-right"%> </li>
<% end %>
</ul>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @restaurant.category %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @restaurant.phone_number %>
</p>

<%#= link_to 'Add new review', new_restaurant_review_path(@restaurant) %>

<p class="mt-3 pt-3 border-top"><strong>Add new review</strong></p>
<!-- POST /restaurants/4/reviews -->
<%= simple_form_for [@restaurant, @review] do |f| %>

  <%= f.error_notification %>

  <% if @review.errors.any? %>
    <div class="alert alert-danger">
      <h3>Please fix these problems:</h3>
      <ul>
      <% @review.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <%= f.input :rating %>
  </div>

  <div class="form-inputs">
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary mb-3' %>
  </div>
<% end %>

<p class="mt-3 pt-3 border-top"><strong>Reviews</strong></p>
<ol class="pl-3">
  <% @restaurant.reviews.each do |review| %>
    <li class="bg-light p-2">
      <p><strong>Rating:</strong> <%= review.rating %></p>
      <p><strong>Content:</strong> <%= review.content %></p>
    </li>
  <% end %>
</ol>

<%#= link_to 'Show chef name', chef_restaurant_path(@restaurant) %>

<%#= link_to 'Edit', edit_restaurant_path(@restaurant) %>